remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: HIKE Tutorial
description: Using the CommonKADS KE methodology to structure Hybrid Intelligence scenarios 
